ITEM_ID_FIELD: item_id
RATING_FIELD: checkin_count
TIME_FIELD: timestamp
USER_ID_FIELD: user_id
benchmark_filename:
- train
- valid
- test
dataset: foursquaretky_sample
epochs: 200
eval_args:
  group_by: user
  order: TO
  split:
    RS:
    - 0.65
    - 0.15
    - 0.2
field_separator: "\t"
filter_inter_by_user_or_item: false
item_inter_num_interval: '[0,inf)'
learning_rate: 0.01
load_col:
  inter:
  - user_id
  - item_id
  - checkin_count
metrics:
- Recall
- MRR
- NDCG
- Hit
- Precision
- MAP
- GiniIndex
- TailPercentage
model: LightGCN
n_layers: 4
reg_weight: 0.001
show_progress: false
topk: 10
train_neg_sample_args:
  uniform: 1
user_inter_num_interval: '[0,inf)'
valid_metric: NDCG@10
