services:
  foursquaretky-car:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld --max-table-size 250 /data/region.osrm
    volumes:
      - ./data/foursquaretky/car:/data
    ports:
      - "5000:5000"
    restart: unless-stopped

  foursquaretky-foot:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld --max-table-size 250 /data/region.osrm
    volumes:
      - ./data/foursquaretky/foot:/data
    ports:
      - "5001:5000"
    restart: unless-stopped

  yelpphl-car:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld --max-table-size 250 /data/region.osrm
    volumes:
      - ./data/yelpphl/car:/data
    ports:
      - "5002:5000"
    restart: unless-stopped

  yelpphl-foot:
    image: osrm/osrm-backend
    command: osrm-routed --algorithm mld --max-table-size 250 /data/region.osrm
    volumes:
      - ./data/yelpphl/foot:/data
    ports:
      - "5003:5000"
    restart: unless-stopped
