import pandas as pd
import json
import os
from globals import BASE_DIR

# The Context-POI general evaluation and the top-k recommendation outputs generated by CAPRI follow a different format than those by RecBole.
# We convert the format to enable a unified evaluation process.

available_datasets = ["snowcard"]

for dataset in available_datasets:
    OUTPUT_DIR = f"{BASE_DIR}{dataset}_dataset/recommendations/"
    recs = os.listdir(OUTPUT_DIR)

    if ".DS_Store" in recs:
        recs.remove(".DS_Store")

    capri_recs = []
    for dir in recs:
        if dir.split("-")[1] == "contextpoi":  # Filter for contextpoi directories
            capri_recs.append(dir)

    for dir in capri_recs:
        dir_path = os.path.join(OUTPUT_DIR, dir)
        files = os.listdir(dir_path)

        eval_file = next((f for f in files if f.startswith("Eval")), None)

        if eval_file:
            eval_csv = os.path.join(dir_path, eval_file)
            json_file = os.path.join(dir_path, "general_evaluation.json")
            eval_df = pd.read_csv(eval_csv)

            metrics = eval_df.iloc[0].to_dict()
            print(f"Metrics for {dir}: {metrics}")

            evaluation_data = {
                "test_result": {
                    "recall@10": metrics.get("recall"),
                    "ndcg@10": metrics.get("ndcg"),
                    "precision@10": metrics.get("precision"),
                    "map@10": metrics.get("map"),
                }
            }

            with open(json_file, "w") as f:
                json.dump(evaluation_data, f, indent=4)

            print(f"Saved general_evaluation.json to {json_file}")
        else:
            print(f"No Eval file found in {dir_path}")

        rec_file = next((f for f in files if f.startswith("Scores")), None)

        if rec_file:
            rec_txt = os.path.join(dir_path, rec_file)
            json_file = os.path.join(dir_path, "top_k_recommendations.json")

            # Initialize the recommendations dictionary
            recommendations = {}

            # Process the CSV file
            with open(rec_txt, "r") as f:
                for line in f:
                    parts = line.strip().split("\t")

                    if len(parts) == 3:
                        user_id = parts[1]  # Second column is the user_id
                        items_with_scores = parts[2].split(
                            ","
                        )  # Third column contains item:score pairs

                        user_id_key = f"{user_id}_x"
                        item_ids = []
                        scores = []

                        for item_score in items_with_scores:
                            item, score = item_score.split(":")
                            item_ids.append(f"{item}_x")
                            scores.append(float(score))

                        # Save data into the recommendations dictionary
                        recommendations[user_id_key] = [
                            {"item_id": item_ids, "score": scores}
                        ]

            # Write to JSON file
            with open(json_file, "w") as f:
                json.dump(recommendations, f, indent=4)

            print(f"Saved top_k_recommendations.json to {json_file}")
